name: wdk_starter_flutter_workspace

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    description: Run `dart analyze` in all packages (infos are fatal in CI).
    exec: dart analyze --fatal-infos
  format:
    description: Verify formatting in all packages.
    exec: dart format --output=none --set-exit-if-changed .
  test:
    description: Run tests in all packages that have them.
    exec: flutter test
    packageFilters:
      dirExists: test
