import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:wdk_flutter/wdk_flutter.dart';

/// Asserts the Dart secret-manager HRPC codecs reproduce Tether's real JS
/// encoders byte-for-byte. Vectors are generated by `tools/parity/oracle.mjs`
/// running the actual `@tetherto/wdk-react-native-provider` codecs over
/// `compact-encoding` (the JS implementation is the oracle).
void main() {
  final List<dynamic> vectors =
      jsonDecode(
            File(
              'test/fixtures/secret_manager_vectors.json',
            ).readAsStringSync(),
          )
          as List<dynamic>;

  test('loaded a non-trivial vector set', () {
    expect(vectors.length, greaterThanOrEqualTo(15));
  });

  group('compact-encoding primitives', () {
    test('uint single-byte and multi-byte varint match', () {
      expect(_hex((CompactEncoder()..uint(0)).takeBytes()), '00');
      expect(_hex((CompactEncoder()..uint(1)).takeBytes()), '01');
      expect(_hex((CompactEncoder()..uint(252)).takeBytes()), 'fc');
      expect(_hex((CompactEncoder()..uint(253)).takeBytes()), 'fdfd00');
      expect(_hex((CompactEncoder()..uint(300)).takeBytes()), 'fd2c01');
    });

    test('string = uint(byteLength) + utf8 bytes; round-trips unicode', () {
      final Uint8List b = (CompactEncoder()..string('héllo 🌍')).takeBytes();
      expect(CompactDecoder(b).string(), 'héllo 🌍');
    });
  });

  group('secret-manager message codecs vs the JS oracle', () {
    test('every vector encodes byte-for-byte identically', () {
      for (final dynamic v in vectors) {
        final String name = v['enc'] as String;
        final Map<String, Object?> value = (v['value'] as Map<String, dynamic>)
            .cast<String, Object?>();
        final String expectedHex = v['hex'] as String;
        final Uint8List bytes = SecretManagerMessages.encode(name, value);
        expect(
          _hex(bytes),
          expectedHex,
          reason: 'encode mismatch for $name $value',
        );
      }
    });

    test('every vector decodes to the same shape as the JS decoder', () {
      for (final dynamic v in vectors) {
        final String name = v['enc'] as String;
        final Map<String, dynamic> expected =
            (v['decoded'] as Map<String, dynamic>);
        final Map<String, Object?> decoded = SecretManagerMessages.decode(
          name,
          _bytes(v['hex'] as String),
        );
        expect(decoded, expected, reason: 'decode mismatch for $name');
      }
    });
  });
}

String _hex(Uint8List b) =>
    b.map((int x) => x.toRadixString(16).padLeft(2, '0')).join();

Uint8List _bytes(String hex) {
  final Uint8List out = Uint8List(hex.length ~/ 2);
  for (int i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}
