import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:wdk_flutter/wdk_flutter.dart';

/// Asserts the Dart **manager** (`@wdk-core`) HRPC codecs reproduce Tether's
/// real JS encoders byte-for-byte. Vectors are generated by
/// `tools/parity/oracle-mgr.mjs` running the autogenerated `messages.js` shipped
/// in `@tetherto/pear-wrk-wdk@1.0.0-beta.4` over `compact-encoding` — the JS
/// implementation is the oracle.
void main() {
  final List<dynamic> bodyVectors =
      jsonDecode(
            File('test/fixtures/wdk_manager_vectors.json').readAsStringSync(),
          )
          as List<dynamic>;
  final List<dynamic> frameVectors =
      jsonDecode(
            File(
              'test/fixtures/wdk_manager_frame_vectors.json',
            ).readAsStringSync(),
          )
          as List<dynamic>;

  test('loaded a non-trivial vector set', () {
    expect(bodyVectors.length, greaterThanOrEqualTo(30));
    expect(frameVectors.length, greaterThanOrEqualTo(5));
  });

  group('manager message codecs vs the JS oracle', () {
    test('every vector encodes byte-for-byte identically', () {
      for (final dynamic v in bodyVectors) {
        final String name = v['enc'] as String;
        final Map<String, Object?> value = (v['value'] as Map<String, dynamic>)
            .cast<String, Object?>();
        final Uint8List bytes = WdkManagerMessages.encode(name, value);
        expect(
          _hex(bytes),
          v['hex'],
          reason: 'encode mismatch for $name $value',
        );
      }
    });

    test('every vector decodes to the same shape as the JS decoder', () {
      for (final dynamic v in bodyVectors) {
        final String name = v['enc'] as String;
        final Map<String, dynamic> expected =
            (v['decoded'] as Map<String, dynamic>);
        final Map<String, Object?> decoded = WdkManagerMessages.decode(
          name,
          _bytes(v['hex'] as String),
        );
        expect(decoded, expected, reason: 'decode mismatch for $name');
      }
    });
  });

  group('manager HRPC frames vs bare-rpc', () {
    test(
      'requests (incl. nested framed options/config) encode byte-for-byte',
      () {
        for (final dynamic v in frameVectors.where(
          (dynamic v) => v['kind'] == 'request',
        )) {
          final Uint8List frame = HrpcFrame.encodeRequest(
            id: v['id'] as int,
            command: v['command'] as int,
            body: _bytes(v['bodyHex'] as String),
          );
          expect(_hex(frame), v['frameHex'], reason: 'request ${v['method']}');
        }
      },
    );

    test('success response encodes + decodes', () {
      final dynamic v = frameVectors.firstWhere(
        (dynamic v) => v['kind'] == 'response',
      );
      final Uint8List frame = HrpcFrame.encodeResponse(
        id: v['id'] as int,
        body: _bytes(v['bodyHex'] as String),
      );
      expect(_hex(frame), v['frameHex']);
      final HrpcMessage msg = HrpcFrame.decode(frame);
      expect(msg.type, HrpcFrame.typeResponse);
      expect(_hex(msg.data!), v['bodyHex']);
    });

    test('error response maps to WdkError (code:5 insufficient balance)', () {
      final dynamic v = frameVectors.firstWhere(
        (dynamic v) => v['kind'] == 'error',
      );
      final Map<String, dynamic> e = v['error'] as Map<String, dynamic>;
      final Uint8List frame = HrpcFrame.encodeError(
        id: v['id'] as int,
        message: e['message'] as String,
        code: e['code'] as String,
        errno: e['errno'] as int,
      );
      expect(_hex(frame), v['frameHex']);
      final HrpcMessage msg = HrpcFrame.decode(frame);
      expect(msg.error, isNotNull);
      expect(msg.error!.code, '5');
    });
  });

  group('HrpcProtocol.wdkManager command table', () {
    test('command ids match @wdk-core/hrpc.json', () {
      final HrpcProtocol p = HrpcProtocol.wdkManager();
      expect(p.methods['workletStart']!.command, 1);
      expect(p.methods['getAddress']!.command, 2);
      expect(p.methods['sendTransaction']!.command, 5);
      expect(p.methods['abstractedAccountTransfer']!.command, 9);
      expect(p.methods['abstractedAccountQuoteTransfer']!.command, 12);
      expect(p.methods['dispose']!.command, 14);
      expect(p.methods['dispose']!.sendOnly, isTrue);
    });
  });

  group('HrpcWorkletRpc round-trip with the manager protocol', () {
    test('getAddress correlates a reply and decodes the address', () async {
      final _LoopbackPipe pipe = _LoopbackPipe();
      pipe.onSend = (Uint8List requestFrame) {
        final HrpcMessage req = HrpcFrame.decode(requestFrame);
        expect(req.command, 2); // getAddress
        final Uint8List body = WdkManagerMessages.encode(
          '@wdk-core/getAddress-response',
          <String, Object?>{'address': 'bc1qexample'},
        );
        pipe.deliver(HrpcFrame.encodeResponse(id: req.id, body: body));
      };

      final HrpcWorkletRpc rpc = HrpcWorkletRpc(
        pipe,
        HrpcProtocol.wdkManager(),
      );
      final WdkManagerRpc manager = WdkManagerRpc(rpc);
      final String address = await manager.getAddress(
        network: 'bitcoin',
        accountIndex: 0,
      );
      expect(address, 'bc1qexample');
      await rpc.close();
    });

    test('dispose is send-only: completes without awaiting a reply', () async {
      final _LoopbackPipe pipe = _LoopbackPipe();
      int sent = 0;
      pipe.onSend = (Uint8List requestFrame) {
        sent++;
        final HrpcMessage req = HrpcFrame.decode(requestFrame);
        expect(req.command, 14); // dispose — and we deliberately never reply
      };
      final HrpcWorkletRpc rpc = HrpcWorkletRpc(
        pipe,
        HrpcProtocol.wdkManager(),
      );
      await WdkManagerRpc(rpc).dispose(); // would hang/timeout if not send-only
      expect(sent, 1);
      await rpc.close();
    });

    test('abstractedAccountTransfer round-trips hash + fee', () async {
      final _LoopbackPipe pipe = _LoopbackPipe();
      pipe.onSend = (Uint8List requestFrame) {
        final HrpcMessage req = HrpcFrame.decode(requestFrame);
        expect(req.command, 9);
        final Uint8List body = WdkManagerMessages.encode(
          '@wdk-core/abstractedAccountTransfer-response',
          <String, Object?>{'hash': '0xabc', 'fee': '1000'},
        );
        pipe.deliver(HrpcFrame.encodeResponse(id: req.id, body: body));
      };
      final HrpcWorkletRpc rpc = HrpcWorkletRpc(
        pipe,
        HrpcProtocol.wdkManager(),
      );
      final Map<String, Object?> r = await WdkManagerRpc(rpc)
          .abstractedAccountTransfer(
            network: 'ethereum',
            accountIndex: 0,
            recipient: '0xR',
            token: '0xT',
            amount: '1000000',
            paymasterTokenAddress: '0xP',
          );
      expect(r['hash'], '0xabc');
      expect(r['fee'], '1000');
      await rpc.close();
    });
  });
}

class _LoopbackPipe implements IpcPipe {
  final StreamController<Uint8List> _ctrl = StreamController<Uint8List>();
  void Function(Uint8List frame)? onSend;

  void deliver(Uint8List bytes) => _ctrl.add(bytes);

  @override
  Stream<Uint8List> get inbound => _ctrl.stream;

  @override
  void send(Uint8List frame) => onSend?.call(frame);

  @override
  Future<void> close() => _ctrl.close();
}

String _hex(Uint8List b) =>
    b.map((int x) => x.toRadixString(16).padLeft(2, '0')).join();

Uint8List _bytes(String hex) {
  final Uint8List out = Uint8List(hex.length ~/ 2);
  for (int i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}
