import 'dart:async';
import 'dart:typed_data';

import 'package:flutter_bare_kit/flutter_bare_kit.dart' as bare;

import 'hrpc_worklet_rpc.dart';
import 'secret_manager_rpc.dart';
import 'wdk_manager_rpc.dart';
import 'worklet_rpc.dart';

/// Adapts a `flutter_bare_kit` [bare.BareIPC] to the RPC layer's [IpcPipe].
/// This is the production transport once the native binding is built.
class BareKitIpcPipe implements IpcPipe {
  BareKitIpcPipe(this._ipc);
  final bare.BareIPC _ipc;

  @override
  Stream<Uint8List> get inbound => _ipc.stream;

  @override
  void send(Uint8List frame) => unawaited(_ipc.write(frame));

  @override
  Future<void> close() => _ipc.end();
}

/// Starts the two WDK worklets via `flutter_bare_kit` and returns the typed
/// RPC wrappers, ready to inject into [WdkService].
///
/// Wire format: both worklets speak **HRPC** (`bare-rpc` framing over
/// `compact-encoding`). The **secret-manager** worklet uses [HrpcWorkletRpc]
/// with [HrpcProtocol.secretManager]; the **manager** (`@wdk-core`) worklet uses
/// [HrpcProtocol.wdkManager]. Both protocols are byte-exact ports of the
/// autogenerated HRPC specs shipped in the pinned `pear-wrk-wdk@beta.4` /
/// `wdk-react-native-provider@beta.3` pair, verified against the real JS
/// encoders (`tools/parity/`).
///
/// Pass [rpcFactory] to override both transports (used by tests/preview).
class WdkWorkletBinding {
  const WdkWorkletBinding._();

  static Future<({SecretManagerRpc secret, WdkManagerRpc manager})> bind({
    required Uint8List managerBundle,
    required Uint8List secretBundle,
    WorkletRpc Function(IpcPipe pipe)? rpcFactory,
  }) async {
    final WorkletRpc Function(IpcPipe) secretMake =
        rpcFactory ??
        (IpcPipe p) => HrpcWorkletRpc(p, HrpcProtocol.secretManager());
    final WorkletRpc Function(IpcPipe) managerMake =
        rpcFactory ??
        (IpcPipe p) => HrpcWorkletRpc(p, HrpcProtocol.wdkManager());

    final bare.Worklet secretW = await bare.Worklet.start(
      '/secret.manager.worklet.bundle',
      bundle: secretBundle,
    );
    final bare.Worklet managerW = await bare.Worklet.start(
      '/wdk.manager.worklet.bundle',
      bundle: managerBundle,
    );

    return (
      secret: SecretManagerRpc(secretMake(BareKitIpcPipe(secretW.ipc))),
      manager: WdkManagerRpc(managerMake(BareKitIpcPipe(managerW.ipc))),
    );
  }
}
