import 'dart:typed_data';

import 'compact_encoding.dart';

/// Byte-exact Dart port of the WDK **manager** (`@wdk-core`) HRPC message
/// codecs — the autogenerated `spec/hrpc/messages.js` shipped in
/// `@tetherto/pear-wrk-wdk@1.0.0-beta.4` (the version `wdk-react-native-provider`
/// @beta.3 pins). Verified against `tools/parity/wdk_manager_vectors.json`,
/// generated by running the real JS encoder over `compact-encoding`.
///
/// Encoding rules reproduced from the generator:
/// - Optional fields are gated by a leading `uint` **flags** byte; a field is
///   "present" by JS truthiness (non-empty string / non-zero number / non-null
///   object). Messages with *no* optional fields have **no** flags byte.
/// - Nested objects (`options`, `config`, `paymasterToken`) are wrapped with
///   `c.frame` = `uint(byteLen) + innerBytes`.
/// - In `abstracted*` requests the `config` flag byte comes **after** the
///   framed `options`, not at the start of the message.
class WdkManagerMessages {
  const WdkManagerMessages._();

  static const String _ns = '@wdk-core';

  static bool _str(Object? v) => v != null && (v as String).isNotEmpty;
  static bool _num(Object? v) => v != null && (v as num) != 0;
  static bool _obj(Object? v) => v != null && v is Map;

  static String _s(Object? v) => (v ?? '') as String;
  static int _u(Object? v) => (v ?? 0) as int;

  static Map<String, Object?> _map(Object? v) =>
      v is Map ? v.cast<String, Object?>() : <String, Object?>{};

  // --- nested sub-objects ----------------------------------------------------

  /// `quoteSendTransaction`/`sendTransaction` options: `{to, value}`.
  static void _encToValue(CompactEncoder e, Map<String, Object?> m) {
    e
      ..string(_s(m['to']))
      ..string(_s(m['value']));
  }

  static Map<String, Object?> _decToValue(CompactDecoder d) =>
      <String, Object?>{'to': d.string(), 'value': d.string()};

  /// `abstracted*` transfer options: `{token, recipient, amount}` (this order).
  static void _encTransferOptions(CompactEncoder e, Map<String, Object?> m) {
    e
      ..string(_s(m['token']))
      ..string(_s(m['recipient']))
      ..string(_s(m['amount']));
  }

  static Map<String, Object?> _decTransferOptions(CompactDecoder d) =>
      <String, Object?>{
        'token': d.string(),
        'recipient': d.string(),
        'amount': d.string(),
      };

  /// `config`: `{ paymasterToken?: { address } }` (flagged optional inner).
  static void _encConfig(CompactEncoder e, Map<String, Object?> m) {
    final bool hasPm = _obj(m['paymasterToken']);
    e.uint(hasPm ? 1 : 0);
    if (hasPm) {
      e.frame((CompactEncoder inner) {
        inner.string(_s(_map(m['paymasterToken'])['address']));
      });
    }
  }

  static Map<String, Object?> _decConfig(CompactDecoder d) {
    final int flags = d.uint();
    return <String, Object?>{
      'paymasterToken': (flags & 1) != 0
          ? d.readFrame(
              (CompactDecoder inner) => <String, Object?>{
                'address': inner.string(),
              },
            )
          : null,
    };
  }

  // --- encode ----------------------------------------------------------------

  /// Encodes [m] for the request/response named [name]; returns the body bytes.
  static Uint8List encode(String name, Map<String, Object?> m) {
    final CompactEncoder e = CompactEncoder();
    switch (name) {
      case '$_ns/log-request':
        final int flags = (_num(m['type']) ? 1 : 0) | (_str(m['data']) ? 2 : 0);
        e.uint(flags);
        if (flags & 1 != 0) e.uint(_u(m['type'])); // log-type enum = uint
        if (flags & 2 != 0) e.string(_s(m['data']));

      case '$_ns/workletStart-request':
        final int flags =
            (_num(m['enableDebugLogs']) ? 1 : 0) |
            (_str(m['seedPhrase']) ? 2 : 0) |
            (_str(m['seedBuffer']) ? 4 : 0);
        e.uint(flags);
        if (flags & 1 != 0) e.uint(_u(m['enableDebugLogs']));
        if (flags & 2 != 0) e.string(_s(m['seedPhrase']));
        if (flags & 4 != 0) e.string(_s(m['seedBuffer']));
        e.string(_s(m['config'])); // non-optional, always present

      case '$_ns/workletStart-response':
        final int flags = _str(m['status']) ? 1 : 0;
        e.uint(flags);
        if (flags & 1 != 0) e.string(_s(m['status']));

      case '$_ns/getAddress-request':
      case '$_ns/getAddressBalance-request':
      case '$_ns/getAbstractedAddress-request':
      case '$_ns/getAbstractedAddressBalance-request':
        e
          ..string(_s(m['network']))
          ..uint(_u(m['accountIndex']));

      case '$_ns/getAddress-response':
      case '$_ns/getAbstractedAddress-response':
        final int flags = _str(m['address']) ? 1 : 0;
        e.uint(flags);
        if (flags & 1 != 0) e.string(_s(m['address']));

      case '$_ns/getAddressBalance-response':
      case '$_ns/getAbstractedAddressBalance-response':
      case '$_ns/getAbstractedAddressTokenBalance-response':
        final int flags = _str(m['balance']) ? 1 : 0;
        e.uint(flags);
        if (flags & 1 != 0) e.string(_s(m['balance']));

      case '$_ns/getAbstractedAddressTokenBalance-request':
        e
          ..string(_s(m['network']))
          ..uint(_u(m['accountIndex']))
          ..string(_s(m['tokenAddress']));

      case '$_ns/quoteSendTransaction-request':
      case '$_ns/sendTransaction-request':
        e
          ..string(_s(m['network']))
          ..uint(_u(m['accountIndex']))
          ..frame(
            (CompactEncoder inner) => _encToValue(inner, _map(m['options'])),
          );

      case '$_ns/quoteSendTransaction-response':
      case '$_ns/abstractedAccountQuoteTransfer-response':
        final int flags = _str(m['fee']) ? 1 : 0;
        e.uint(flags);
        if (flags & 1 != 0) e.string(_s(m['fee']));

      case '$_ns/sendTransaction-response':
        final int flags = (_str(m['fee']) ? 1 : 0) | (_str(m['hash']) ? 2 : 0);
        e.uint(flags);
        if (flags & 1 != 0) e.string(_s(m['fee']));
        if (flags & 2 != 0) e.string(_s(m['hash']));

      case '$_ns/abstractedAccountTransfer-request':
      case '$_ns/abstractedAccountQuoteTransfer-request':
        final bool hasConfig = _obj(m['config']);
        e
          ..string(_s(m['network']))
          ..uint(_u(m['accountIndex']))
          ..frame(
            (CompactEncoder inner) =>
                _encTransferOptions(inner, _map(m['options'])),
          )
          ..uint(hasConfig ? 1 : 0);
        if (hasConfig) {
          e.frame(
            (CompactEncoder inner) => _encConfig(inner, _map(m['config'])),
          );
        }

      case '$_ns/abstractedAccountTransfer-response':
      case '$_ns/abstractedSendTransaction-response':
        final int flags = (_str(m['hash']) ? 1 : 0) | (_str(m['fee']) ? 2 : 0);
        e.uint(flags);
        if (flags & 1 != 0) e.string(_s(m['hash']));
        if (flags & 2 != 0) e.string(_s(m['fee']));

      case '$_ns/getApproveTransaction-request':
        _encTransferOptions(e, m); // {token, recipient, amount}

      case '$_ns/getApproveTransaction-response':
        e
          ..string(_s(m['to']))
          ..string(_s(m['value']))
          ..string(_s(m['data']));

      case '$_ns/abstractedSendTransaction-request':
        final bool hasConfig = _obj(m['config']);
        e
          ..string(_s(m['network']))
          ..uint(_u(m['accountIndex']))
          ..string(
            _s(m['options']),
          ) // options is a JSON string here, not framed
          ..uint(hasConfig ? 1 : 0);
        if (hasConfig) {
          e.frame(
            (CompactEncoder inner) => _encConfig(inner, _map(m['config'])),
          );
        }

      case '$_ns/getTransactionReceipt-request':
        e
          ..string(_s(m['network']))
          ..uint(_u(m['accountIndex']))
          ..string(_s(m['hash']));

      case '$_ns/getTransactionReceipt-response':
        final int flags = _str(m['receipt']) ? 1 : 0;
        e.uint(flags);
        if (flags & 1 != 0) e.string(_s(m['receipt']));

      case '$_ns/dispose-request':
        break; // empty body

      default:
        throw ArgumentError('Unknown manager message: $name');
    }
    return e.takeBytes();
  }

  // --- decode ----------------------------------------------------------------

  /// Decodes the message [name] from [bytes], mirroring the JS decode shapes
  /// (absent strings → null, absent numbers → 0, absent objects → null).
  static Map<String, Object?> decode(String name, Uint8List bytes) {
    final CompactDecoder d = CompactDecoder(bytes);
    switch (name) {
      case '$_ns/log-request':
        final int flags = d.uint();
        return <String, Object?>{
          'type': flags & 1 != 0 ? d.uint() : 0,
          'data': flags & 2 != 0 ? d.string() : null,
        };

      case '$_ns/workletStart-request':
        final int flags = d.uint();
        return <String, Object?>{
          'enableDebugLogs': flags & 1 != 0 ? d.uint() : 0,
          'seedPhrase': flags & 2 != 0 ? d.string() : null,
          'seedBuffer': flags & 4 != 0 ? d.string() : null,
          'config': d.string(),
        };

      case '$_ns/workletStart-response':
        return <String, Object?>{
          'status': d.uint() & 1 != 0 ? d.string() : null,
        };

      case '$_ns/getAddress-request':
      case '$_ns/getAddressBalance-request':
      case '$_ns/getAbstractedAddress-request':
      case '$_ns/getAbstractedAddressBalance-request':
        return <String, Object?>{
          'network': d.string(),
          'accountIndex': d.uint(),
        };

      case '$_ns/getAddress-response':
      case '$_ns/getAbstractedAddress-response':
        return <String, Object?>{
          'address': d.uint() & 1 != 0 ? d.string() : null,
        };

      case '$_ns/getAddressBalance-response':
      case '$_ns/getAbstractedAddressBalance-response':
      case '$_ns/getAbstractedAddressTokenBalance-response':
        return <String, Object?>{
          'balance': d.uint() & 1 != 0 ? d.string() : null,
        };

      case '$_ns/getAbstractedAddressTokenBalance-request':
        return <String, Object?>{
          'network': d.string(),
          'accountIndex': d.uint(),
          'tokenAddress': d.string(),
        };

      case '$_ns/quoteSendTransaction-request':
      case '$_ns/sendTransaction-request':
        return <String, Object?>{
          'network': d.string(),
          'accountIndex': d.uint(),
          'options': d.readFrame(_decToValue),
        };

      case '$_ns/quoteSendTransaction-response':
      case '$_ns/abstractedAccountQuoteTransfer-response':
        return <String, Object?>{'fee': d.uint() & 1 != 0 ? d.string() : null};

      case '$_ns/sendTransaction-response':
        final int flags = d.uint();
        return <String, Object?>{
          'fee': flags & 1 != 0 ? d.string() : null,
          'hash': flags & 2 != 0 ? d.string() : null,
        };

      case '$_ns/abstractedAccountTransfer-request':
      case '$_ns/abstractedAccountQuoteTransfer-request':
        final String network = d.string();
        final int accountIndex = d.uint();
        final Map<String, Object?> options = d.readFrame(_decTransferOptions);
        final int flags = d.uint();
        return <String, Object?>{
          'network': network,
          'accountIndex': accountIndex,
          'options': options,
          'config': flags & 1 != 0 ? d.readFrame(_decConfig) : null,
        };

      case '$_ns/abstractedAccountTransfer-response':
      case '$_ns/abstractedSendTransaction-response':
        final int flags = d.uint();
        return <String, Object?>{
          'hash': flags & 1 != 0 ? d.string() : null,
          'fee': flags & 2 != 0 ? d.string() : null,
        };

      case '$_ns/getApproveTransaction-request':
        return _decTransferOptions(d);

      case '$_ns/getApproveTransaction-response':
        return <String, Object?>{
          'to': d.string(),
          'value': d.string(),
          'data': d.string(),
        };

      case '$_ns/abstractedSendTransaction-request':
        final String network = d.string();
        final int accountIndex = d.uint();
        final String options = d.string();
        final int flags = d.uint();
        return <String, Object?>{
          'network': network,
          'accountIndex': accountIndex,
          'options': options,
          'config': flags & 1 != 0 ? d.readFrame(_decConfig) : null,
        };

      case '$_ns/getTransactionReceipt-request':
        return <String, Object?>{
          'network': d.string(),
          'accountIndex': d.uint(),
          'hash': d.string(),
        };

      case '$_ns/getTransactionReceipt-response':
        return <String, Object?>{
          'receipt': d.uint() & 1 != 0 ? d.string() : null,
        };

      case '$_ns/dispose-request':
        return <String, Object?>{};

      default:
        throw ArgumentError('Unknown manager message: $name');
    }
  }
}
